version: "3.7"

services:
  app:
    build: .
    container_name: "server-app-service"
    ports:
      - ${PORT}:${PORT}
    working_dir: /app

    volumes:
      - .:/app
    links:
      - mongodb
    env_file:
      - .env.development
    command: ["npm", "start"]

  mongodb:
    image: mongo:latest
    container_name: "mongo-db-service"
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
