version: "3.7"

services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - .:/app
    links:
      - mongodb
    env_file:
      - .env.development
    #command: ["npm", "start"]

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
