version: "3.7"

services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    # we can also add .env.* file to the project
    env_file: .env
    volumes:
      - .:/app
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
