version: "3.7"

services:
  app:
    build: .
    ports:
      - 5000:5000
    working_dir: /app
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/beta1
    volumes:
      - .:/app
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
