# [INCOMPLETE] This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master, develop]
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      [master, develop]
      # Ignore updates on Readme file
    paths-ignore:
      - "**.md"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # job 1: greet the user
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }} 🐴!! Starting the build..."

  # job 2: checking eslinting issues
  checking_styling_issues:
    runs-on: ubuntu-latest
    needs: [greet] # the following jobs must be fulfilled to run this job

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout reporsitory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SQUID_BOT_ACCESS_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install yarn
        run: npm install -g yarn

      - name: Install project packages
        run: yarn install --frozen-lockfile

      - name: Running linter
        run: npm run lint_check

      - name: Running style check
        run: npm run prettier_check

      - name: Success
        run: |
          echo "Code style and syntax checking was successful 🎉"

  # job 3: unit testing using docker container
  unit_testing:
    runs-on: ubuntu-latest
    needs: [greet]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout reporsitory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SQUID_BOT_ACCESS_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install yarn
        run: npm install -g yarn

      - name: Install project packages
        run: yarn install --frozen-lockfile

      - name: Running unit tests
        run: yarn run docker-test

      - name: Success
        run: |
          echo "All unit tests passed! 🎉"
